{% set version = "4.5.1" %}

package:
    name: qutip
    version: {{ version }}

source:
    url: http://qutip.org/downloads/{{ version }}/qutip-{{ version }}.tar.gz
    sha256: 687e216aaeafdbbc47b61d7b210c0f07206e73c28afd987473cf6b292a6101cb

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"  # [not win]
    skip: True                        # [py2k]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy {{ numpy }}
    - cython >=0.21
    - scipy >=1.0
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0

test:
  imports:
    - qutip

about:
    home: http://qutip.org
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
    - quantshah
    - nathanshammah
    - nonhermitian
    - ericgig
    - nathanshammah
