{% set version = "4.0.1" %}

package:
    name: qutip
    version: {{ version }}

source:
    fn: qutip-{{ version }}.tar.gz
    url: http://qutip.org/downloads/{{ version }}/qutip-{{ version }}.tar.gz
    sha256: 77751f7dd97da0eef39f5913e7d7a610638a86241ea0a879233f298fb6bfe243

build:
    number: 0
    script: $PYTHON setup.py install  # [unix]
    skip: True                        # [win and py35]

requirements:
  build:
    - python
    - setuptools
    - cython >=0.15
    - numpy x.x
    - mingwpy                         # [win]
    
  run:
    - python
    - numpy x.x
    - scipy >=0.14
    - cython >=0.15
    - mingwpy                         # [win]
    
test:
  imports:
    - qutip

about:
    home: http://qutip.org
    license: BSD 3-clause
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
    - sahmed95
