{% set version = "3.1.0" %}

package:
    name: qutip
    version: {{ version }}

source:
    fn: qutip-{{ version }}.tar.gz
    url: http://qutip.org/downloads/{{ version }}/qutip-{{ version }}.tar.gz
    sha256: 078399c9830c011ec189db222fcd45f71d2a135800874784d8386d67b4357402
    patches:
      - qutip__init__.patch

build:
    number: 0
    script: $PYTHON setup.py install
    skip: True       # [win and py3k]

requirements:
  build:
    - python
    - cython >=0.15
    - numpy x.x
    - mingwpy        # [win]
    
  run:
    - python
    - numpy x.x
    - scipy >=0.14

test:
  imports:
    - qutip

about:
    home: http://qutip.org
    license: BSD 3-clause
    summary: 'QuTiP is open-source software for simulating the dynamics of open quantum systems and optimal quantum control'

extra:
  recipe-maintainers:
    - ajgpitch
