travis:
  secure:
    BINSTAR_TOKEN: qkIGvyI2pcaxtR7RxctXJOPyERS2WcdW4oUinz2m8WUu1C1JRPFr//YawnOhVYUYqywrFLqIC8KOpFjRbU/WaN+tz/GvaUTH/VENcnYzJI3vH7YIPwic4H0qTdQtWipQY+8KIdFSClsV86eTaxhDciooECOlXZCpiMf0TJrw9HHquJv7zD9ctwp82d7Fsh3lAyVlQWD16EiQhlmVjz5OXasAJBMQY3tv19F7uyaGUUxgjUVCzORExBG349a9uFVIauzFvl8NAiGWgzOZaiMIBGtmzZlu7wy1GzDVAeQywcKOiakzD4Pt9Lazu6ehkPlVIHG+BAn7wqMDt4vvG1rKTH6V9EtRqoLryGaq8IMUZGl1rcki/TG9LgOeAIGMI+dnmWxmWCToC/uuMkuIOiXbzfOmoVqv9UdM3svYzA4A6+zHr8N3rC2mv72eU+SGRDuJKqNtnEyCEi5KhjdrnWx+q3LExUXQQDvO22o7bTlDpOBycNc4erdASE779rLXmBMgWLpbYzlaDcXOltuXk9ak2EdZ9XoC23ra2lvfY4Sy98SiSLVHDQasw2FT5ZzWR+Tpo0q3PP4RqXCw6ISWL5vC2mgJTwy6hXVw4pJdvATcUoafLmJX+EEWDzXa3HhfkWMPEc4KI0JvbunNR9i9yEiR5n6Y2TxOplkNRZB0bA01w+E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
